#!/usr/bin/env bash
# Ice-Panel one-command installer.
#
# What it does:
#   1. Verifies Docker + Compose plugin (installs them on Ubuntu/Debian if missing)
#   2. Clones this repo into $ICE_PANEL_DIR (default /opt/ice-panel)
#   3. Generates `.env.production` with random JWT_SECRET + Postgres password
#   4. Builds the panel-backend / panel-frontend images locally
#   5. Runs Prisma migrate deploy (one-shot service)
#   6. Brings up the full stack and waits for health
#
# Idempotent — safe to rerun. Won't overwrite an existing .env.production.
#
# Usage (as root):
#   bash <(curl -fsSL https://raw.githubusercontent.com/0xIC3/Ice-Panel/main/scripts/install-panel.sh)
#
# Or with a specific tag/branch:
#   ICE_PANEL_REF=v0.1.0 bash <(curl ...)
#
# Customisation via env:
#   ICE_PANEL_DIR        Install dir (default /opt/ice-panel)
#   ICE_PANEL_REPO       Git URL (default https://github.com/0xIC3/Ice-Panel.git)
#   ICE_PANEL_REF        Branch/tag/sha (default main)
#   FRONTEND_PORT        Host port the SPA listens on (default 8080)
#   CORS_ORIGIN          Allowed origin for the API (default http://<vps-ip>:<FRONTEND_PORT>)

set -euo pipefail

log()  { printf '\033[1;34m[install-panel]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "Must run as root (sudo bash $0)"

ICE_PANEL_DIR=${ICE_PANEL_DIR:-/opt/ice-panel}
ICE_PANEL_REPO=${ICE_PANEL_REPO:-https://github.com/0xIC3/Ice-Panel.git}
ICE_PANEL_REF=${ICE_PANEL_REF:-main}
FRONTEND_PORT=${FRONTEND_PORT:-8080}

# ───── 1. Distro check ─────
if [[ ! -r /etc/os-release ]]; then
  fail "Cannot read /etc/os-release; only Ubuntu/Debian supported here"
fi
. /etc/os-release
case "${ID:-}" in
  ubuntu|debian) ;;
  *) fail "Only Ubuntu/Debian are supported. Detected ID=${ID:-unknown}." ;;
esac
log "Detected $PRETTY_NAME"

# ───── 2. Docker ─────
if ! command -v docker >/dev/null; then
  log "Installing Docker (official repo)"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/${ID}/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
log "Docker: $(docker --version)"
log "Compose: $(docker compose version)"

# ───── 3. Source checkout ─────
if [[ ! -d "$ICE_PANEL_DIR/.git" ]]; then
  log "Cloning $ICE_PANEL_REPO@$ICE_PANEL_REF into $ICE_PANEL_DIR"
  apt-get install -y git
  git clone --depth 1 --branch "$ICE_PANEL_REF" "$ICE_PANEL_REPO" "$ICE_PANEL_DIR"
else
  log "Updating existing checkout at $ICE_PANEL_DIR"
  git -C "$ICE_PANEL_DIR" fetch --depth 1 origin "$ICE_PANEL_REF"
  git -C "$ICE_PANEL_DIR" checkout "$ICE_PANEL_REF"
  git -C "$ICE_PANEL_DIR" reset --hard "origin/$ICE_PANEL_REF" || true
fi
cd "$ICE_PANEL_DIR"

# ───── 4. .env.production ─────
ENV_FILE="$ICE_PANEL_DIR/.env.production"
if [[ -f "$ENV_FILE" ]]; then
  log ".env.production already exists; keeping current secrets"
else
  log "Generating .env.production with fresh secrets"
  PG_PASSWORD=$(head -c 24 /dev/urandom | base64 | tr -d '+/=' | head -c 32)
  JWT_SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '+/=' | head -c 64)
  PUBLIC_IP=$(curl -fsSL https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
  CORS_ORIGIN_VAL=${CORS_ORIGIN:-http://${PUBLIC_IP}:${FRONTEND_PORT}}
  cat > "$ENV_FILE" <<EOF
# Generated by install-panel.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_USER=icepanel
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=icepanel

DATABASE_URL=postgres://icepanel:${PG_PASSWORD}@postgres:5432/icepanel
REDIS_URL=redis://redis:6379

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=24h
LOG_LEVEL=info

CORS_ORIGIN=${CORS_ORIGIN_VAL}
FRONTEND_PORT=${FRONTEND_PORT}
EOF
  chmod 600 "$ENV_FILE"
fi

# ───── 5. Build images ─────
log "Building backend + frontend images (first run takes 5-10 min)"
docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" build

# ───── 6. Migrate ─────
log "Running Prisma migrations"
docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" run --rm migrate

# ───── 7. Up ─────
log "Starting full stack"
docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" up -d

# ───── 8. Wait for health ─────
log "Waiting for backend /health to return 200 (up to 60s)"
for i in $(seq 1 60); do
  if docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" exec -T backend \
       wget -qO- http://127.0.0.1:3000/health 2>/dev/null | grep -q '"status":"ok"'; then
    log "Backend is healthy"
    break
  fi
  sleep 1
  if [[ $i -eq 60 ]]; then
    warn "Backend didn't reach /health within 60s — check logs:"
    warn "  docker compose -f $ICE_PANEL_DIR/docker-compose.prod.yml logs backend"
  fi
done

# ───── 9. Done ─────
PUBLIC_IP=$(curl -fsSL https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
echo
log "🎉 Ice-Panel is running."
echo
echo "  SPA:        http://${PUBLIC_IP}:${FRONTEND_PORT}"
echo "  API:        http://${PUBLIC_IP}:${FRONTEND_PORT}/api"
echo "  Install dir: ${ICE_PANEL_DIR}"
echo "  .env file:   ${ENV_FILE}  (chmod 600 — keep it secret)"
echo
echo "Next steps:"
echo "  1. Open the SPA — you'll see the 'Create first admin' form."
echo "  2. Front this with Caddy/Traefik for HTTPS before exposing publicly."
echo "  3. Provision a node:  bash <(curl -fsSL .../install-node.sh)"
echo
echo "Common ops:"
echo "  cd ${ICE_PANEL_DIR}"
echo "  docker compose -f docker-compose.prod.yml --env-file .env.production logs -f"
echo "  docker compose -f docker-compose.prod.yml --env-file .env.production restart backend"
echo "  git pull && docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build"
